baseURL: http://example.org/
languageCode: en-us
title: My New Hugo Site

module:
  imports:
  - path: github.com/hugomods/icons/vendors/bootstrap
  - path: github.com/hugomods/images
  - path: github.com/hugomods/bootstrap
  - path: github.com/hugomods/katex
